from __future__ import annotations


TABLE_KEYWORDS = {
    "core_performance_indicators_sheet": [
        "主要会计数据",
        "主要财务指标",
        "主要会计数据和财务指标",
        "主要财务数据",
    ],
    "balance_sheet": ["资产负债表", "合并资产负债表"],
    "cash_flow_sheet": ["现金流量表", "合并现金流量表"],
    "income_sheet": ["利润表", "合并利润表"],
}


FIELD_ALIASES = {
    "core_performance_indicators_sheet": {
        "营业收入": "total_operating_revenue",
        "每股收益": "eps",
        "基本每股收益": "eps",
        "营业总收入": "total_operating_revenue",
        "营业总收入同比增长": "operating_revenue_yoy_growth",
        "营业总收入比上年同期增长": "operating_revenue_yoy_growth",
        "营业总收入较上年同期增长": "operating_revenue_yoy_growth",
        "营业总收入环比增长": "operating_revenue_qoq_growth",
        "归属于上市公司股东的净利润": "net_profit_10k_yuan",
        "归属于上市公司股东的净利润同比增长": "net_profit_yoy_growth",
        "归属于上市公司股东的净利润环比增长": "net_profit_qoq_growth",
        "每股净资产": "net_asset_per_share",
        "净资产收益率": "roe",
        "加权平均净资产收益率": "roe",
        "经营活动产生的现金流量净额/每股": "operating_cf_per_share",
        "每股经营现金流": "operating_cf_per_share",
        "扣除非经常性损益后的净利润": "net_profit_excl_non_recurring",
        "归属于上市公司股东的扣除非经常性损益的净利润": "net_profit_excl_non_recurring",
        "归属于本公司股东的扣除非经常性损益的净利润": "net_profit_excl_non_recurring",
        "归属于本公司股东的每股股东权益": "net_asset_per_share",
        "扣除非经常性损益后的净利润同比增长": "net_profit_excl_non_recurring_yoy",
        "毛利率": "gross_profit_margin",
        "净利率": "net_profit_margin",
        "扣非加权平均净资产收益率": "roe_weighted_excl_non_recurring",
        "扣除非经常性损益后的加权平均净资产收益率": "roe_weighted_excl_non_recurring",
    },
    "balance_sheet": {
        "货币资金": "asset_cash_and_cash_equivalents",
        "现金及存放中央银行款项": "asset_cash_and_cash_equivalents",
        "现金及银行存款": "asset_cash_and_cash_equivalents",
        "应收账款": "asset_accounts_receivable",
        "存货": "asset_inventory",
        "交易性金融资产": "asset_trading_financial_assets",
        "在建工程": "asset_construction_in_progress",
        "资产总计": "asset_total_assets",
        "总资产同比增长": "asset_total_assets_yoy_growth",
        "应付账款": "liability_accounts_payable",
        "预收款项": "liability_advance_from_customers",
        "预收账款": "liability_advance_from_customers",
        "负债合计": "liability_total_liabilities",
        "总负债同比增长": "liability_total_liabilities_yoy_growth",
        "合同负债": "liability_contract_liabilities",
        "合同负债及预收款项": "liability_contract_liabilities",
        "短期借款": "liability_short_term_loans",
        "短期银行借款": "liability_short_term_loans",
        "资产负债率": "asset_liability_ratio",
        "未分配利润": "equity_unappropriated_profit",
        "归属于母公司股东的未分配利润": "equity_unappropriated_profit",
        "所有者权益合计": "equity_total_equity",
        "股东权益合计": "equity_total_equity",
        "归属于母公司股东权益合计": "equity_total_equity",
    },
    "cash_flow_sheet": {
        "现金及现金等价物净增加额": "net_cash_flow",
        "现金及现金等价物净增加额同比增长": "net_cash_flow_yoy_growth",
        "经营活动产生的现金流量净额": "operating_cf_net_amount",
        "经营活动现金流占比": "operating_cf_ratio_of_net_cf",
        "销售商品、提供劳务收到的现金": "operating_cf_cash_from_sales",
        "投资活动产生的现金流量净额": "investing_cf_net_amount",
        "投资活动现金流占比": "investing_cf_ratio_of_net_cf",
        "购建固定资产、无形资产和其他长期资产支付的现金": "investing_cf_cash_for_investments",
        "购建固定资产、无形资产和其他长期资产所支付的现金": "investing_cf_cash_for_investments",
        "投资支付的现金": "investing_cf_cash_for_investments",
        "收回投资收到的现金": "investing_cf_cash_from_investment_recovery",
        "收回投资所收到的现金": "investing_cf_cash_from_investment_recovery",
        "取得借款收到的现金": "financing_cf_cash_from_borrowing",
        "借款收到的现金": "financing_cf_cash_from_borrowing",
        "偿还债务支付的现金": "financing_cf_cash_for_debt_repayment",
        "偿还借款支付的现金": "financing_cf_cash_for_debt_repayment",
        "筹资活动产生的现金流量净额": "financing_cf_net_amount",
        "筹资活动现金流占比": "financing_cf_ratio_of_net_cf",
    },
    "income_sheet": {
        "净利润": "net_profit",
        "净利润同比增长": "net_profit_yoy_growth",
        "其他收益": "other_income",
        "营业总收入": "total_operating_revenue",
        "营业总收入同比增长": "operating_revenue_yoy_growth",
        "营业成本": "operating_expense_cost_of_sales",
        "销售费用": "operating_expense_selling_expenses",
        "管理费用": "operating_expense_administrative_expenses",
        "财务费用": "operating_expense_financial_expenses",
        "研发费用": "operating_expense_rnd_expenses",
        "研发投入": "operating_expense_rnd_expenses",
        "研发支出": "operating_expense_rnd_expenses",
        "税金及附加": "operating_expense_taxes_and_surcharges",
        "营业总成本": "total_operating_expenses",
        "营业利润": "operating_profit",
        "利润总额": "total_profit",
        "资产减值损失": "asset_impairment_loss",
        "信用减值损失": "credit_impairment_loss",
    },
}


TABLE_REQUIRED_COLUMNS = {
    "core_performance_indicators_sheet": [
        "serial_number",
        "stock_code",
        "stock_abbr",
        "report_period",
        "report_year",
    ],
    "balance_sheet": [
        "serial_number",
        "stock_code",
        "stock_abbr",
        "report_period",
        "report_year",
    ],
    "cash_flow_sheet": [
        "serial_number",
        "stock_code",
        "stock_abbr",
        "report_period",
        "report_year",
    ],
    "income_sheet": [
        "serial_number",
        "stock_code",
        "stock_abbr",
        "report_period",
        "report_year",
    ],
}
